apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: apps
    repoURL: https://github.com/jaimejorge/techweek-gitops-infra-code.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
